import type { IconType } from "react-icons";
import {
  FaAmbulance,
  FaArchive,
  FaBalanceScale,
  FaBook,
  FaBookMedical,
  FaBookOpen,
  FaBookmark,
  FaBriefcase,
  FaBriefcaseMedical,
  FaBuilding,
  FaCalculator,
  FaCalendarAlt,
  FaCertificate,
  FaChartBar,
  FaCheckCircle,
  FaCity,
  FaClipboard,
  FaClipboardCheck,
  FaClipboardList,
  FaCog,
  FaFile,
  FaFileAlt,
  FaFileArchive,
  FaFileContract,
  FaFileInvoice,
  FaFileMedical,
  FaFileSignature,
  FaFirstAid,
  FaFlag,
  FaHandHoldingMedical,
  FaHeartbeat,
  FaHospital,
  FaIndustry,
  FaKey,
  FaLightbulb,
  FaMicroscope,
  FaNewspaper,
  FaNotesMedical,
  FaPills,
  FaPrescriptionBottleAlt,
  FaProjectDiagram,
  FaSchool,
  FaScroll,
  FaSearch,
  FaShieldAlt,
  FaSitemap,
  FaStar,
  FaStethoscope,
  FaSyringe,
  FaTag,
  FaTasks,
  FaTools,
  FaUniversity,
  FaUserCog,
  FaUserMd,
  FaUserShield,
  FaUserTie,
  FaUsers,
} from "react-icons/fa";

import { HiAcademicCap, HiArchiveBox, HiBookmark, HiBuildingOffice, HiCalendar, HiChartBar, HiClipboardDocumentCheck, HiCog, HiDocument, HiDocumentText, HiLightBulb, HiStar } from "react-icons/hi2";

import { LuBadgeCheck, LuBookOpen, LuBuilding2, LuChartBar, LuCircleAlert, LuFileLock, LuFileText, LuFlag, LuFolder, LuHospital, LuKeyRound, LuLayers, LuListChecks, LuPill, LuSettings, LuShieldCheck, LuStar, LuStethoscope, LuUser, LuUserCog, LuUsers, LuWrench } from "react-icons/lu";

import { PiAmbulance, PiArchive, PiBookOpen, PiBookmarkSimple, PiBuildings, PiCertificate, PiChartBar, PiClipboardText, PiFileText, PiFlagPennant, PiFolder, PiFolders, PiGear, PiHospital, PiKey, PiLightbulb, PiListChecks, PiPill, PiShieldCheck, PiStar, PiStethoscope, PiUserCircle, PiUserGear, PiUsersFour } from "react-icons/pi";

import { TbCertificate, TbClipboardCheck, TbClipboardList, TbFlag, TbFolders, TbHeartRateMonitor, TbHospital, TbReportMedical, TbSettings, TbStethoscope, TbTemplate, TbUser, TbUsers, TbUsersGroup } from "react-icons/tb";

export type FolderIconId = string;

export type IconGroupId = "salud" | "documentos" | "procesos" | "organizacion" | "general";

export interface IconEntry {
  id: FolderIconId;
  label: string;
  Component: IconType;
  group: IconGroupId;
}

export const ICON_GROUPS: { id: IconGroupId; label: string }[] = [
  { id: "salud", label: "Salud" },
  { id: "documentos", label: "Documentos" },
  { id: "procesos", label: "Procesos" },
  { id: "organizacion", label: "Organización" },
  { id: "general", label: "General" },
];

export const ICON_CATALOG: IconEntry[] = [
  //* Salud (15)
  { id: "fa-hospital", label: "Hospital", Component: FaHospital, group: "salud" },
  { id: "pi-hospital", label: "Hospital", Component: PiHospital, group: "salud" },
  { id: "lu-hospital", label: "Hospital", Component: LuHospital, group: "salud" },
  { id: "tb-hospital", label: "Hospital", Component: TbHospital, group: "salud" },
  { id: "fa-user-md", label: "Médico", Component: FaUserMd, group: "salud" },
  { id: "fa-stethoscope", label: "Estetoscopio", Component: FaStethoscope, group: "salud" },
  { id: "tb-stethoscope", label: "Estetoscopio", Component: TbStethoscope, group: "salud" },
  { id: "lu-stethoscope", label: "Estetoscopio", Component: LuStethoscope, group: "salud" },
  { id: "pi-stethoscope", label: "Estetoscopio", Component: PiStethoscope, group: "salud" },
  { id: "fa-heartbeat", label: "Pulso", Component: FaHeartbeat, group: "salud" },
  { id: "tb-heart-rate-monitor", label: "Monitor", Component: TbHeartRateMonitor, group: "salud" },
  { id: "fa-pills", label: "Medicamentos", Component: FaPills, group: "salud" },
  { id: "lu-pill", label: "Píldora", Component: LuPill, group: "salud" },
  { id: "pi-pill", label: "Píldora", Component: PiPill, group: "salud" },
  { id: "fa-syringe", label: "Jeringa", Component: FaSyringe, group: "salud" },
  { id: "fa-ambulance", label: "Ambulancia", Component: FaAmbulance, group: "salud" },
  { id: "pi-ambulance", label: "Ambulancia", Component: PiAmbulance, group: "salud" },
  { id: "fa-first-aid", label: "Primeros auxilios", Component: FaFirstAid, group: "salud" },
  { id: "fa-hand-holding-medical", label: "Atención", Component: FaHandHoldingMedical, group: "salud" },
  { id: "fa-briefcase-medical", label: "Maletín médico", Component: FaBriefcaseMedical, group: "salud" },
  { id: "fa-microscope", label: "Microscopio", Component: FaMicroscope, group: "salud" },
  { id: "fa-prescription-bottle", label: "Receta", Component: FaPrescriptionBottleAlt, group: "salud" },
  { id: "fa-book-medical", label: "Manual clínico", Component: FaBookMedical, group: "salud" },
  { id: "fa-notes-medical", label: "Notas clínicas", Component: FaNotesMedical, group: "salud" },
  { id: "fa-file-medical", label: "Historia clínica", Component: FaFileMedical, group: "salud" },
  { id: "fa-shield-alt", label: "Protección", Component: FaShieldAlt, group: "salud" },
  { id: "tb-report-medical", label: "Reporte médico", Component: TbReportMedical, group: "salud" },

  //* Documentos (12)
  { id: "fa-folder", label: "Carpeta", Component: FaArchive, group: "documentos" },
  { id: "lu-folder", label: "Carpeta", Component: LuFolder, group: "documentos" },
  { id: "pi-folder", label: "Carpeta", Component: PiFolder, group: "documentos" },
  { id: "pi-folders", label: "Carpetas", Component: PiFolders, group: "documentos" },
  { id: "tb-folders", label: "Carpetas", Component: TbFolders, group: "documentos" },
  { id: "fa-file", label: "Archivo", Component: FaFile, group: "documentos" },
  { id: "lu-file-text", label: "Documento", Component: LuFileText, group: "documentos" },
  { id: "fa-file-alt", label: "Documento", Component: FaFileAlt, group: "documentos" },
  { id: "hi-document", label: "Documento", Component: HiDocument, group: "documentos" },
  { id: "pi-file-text", label: "Documento", Component: PiFileText, group: "documentos" },
  { id: "hi-document-text", label: "Documento de texto", Component: HiDocumentText, group: "documentos" },
  { id: "fa-file-archive", label: "Archivo", Component: FaFileArchive, group: "documentos" },
  { id: "fa-archive", label: "Archivado", Component: FaArchive, group: "documentos" },
  { id: "hi-archive", label: "Archivado", Component: HiArchiveBox, group: "documentos" },
  { id: "pi-archive", label: "Archivado", Component: PiArchive, group: "documentos" },
  { id: "fa-book", label: "Libro", Component: FaBook, group: "documentos" },
  { id: "fa-book-open", label: "Libro abierto", Component: FaBookOpen, group: "documentos" },
  { id: "lu-book-open", label: "Libro abierto", Component: LuBookOpen, group: "documentos" },
  { id: "pi-book-open", label: "Libro abierto", Component: PiBookOpen, group: "documentos" },
  { id: "hi-academic-cap", label: "Académico", Component: HiAcademicCap, group: "documentos" },
  { id: "fa-scroll", label: "Normativa", Component: FaScroll, group: "documentos" },
  { id: "fa-certificate", label: "Certificado", Component: FaCertificate, group: "documentos" },
  { id: "pi-certificate", label: "Certificado", Component: PiCertificate, group: "documentos" },
  { id: "tb-certificate", label: "Certificado", Component: TbCertificate, group: "documentos" },
  { id: "fa-clipboard", label: "Portapapeles", Component: FaClipboard, group: "documentos" },
  { id: "fa-clipboard-list", label: "Lista", Component: FaClipboardList, group: "documentos" },
  { id: "fa-newspaper", label: "Publicación", Component: FaNewspaper, group: "documentos" },
  { id: "fa-file-contract", label: "Contrato", Component: FaFileContract, group: "documentos" },
  { id: "fa-file-signature", label: "Firma", Component: FaFileSignature, group: "documentos" },
  { id: "fa-file-invoice", label: "Factura", Component: FaFileInvoice, group: "documentos" },
  { id: "lu-file-lock", label: "Confidencial", Component: LuFileLock, group: "documentos" },

  //* Procesos (10)
  { id: "fa-cog", label: "Configuración", Component: FaCog, group: "procesos" },
  { id: "pi-cog", label: "Configuración", Component: PiGear, group: "procesos" },
  { id: "hi-cog", label: "Configuración", Component: HiCog, group: "procesos" },
  { id: "lu-settings", label: "Ajustes", Component: LuSettings, group: "procesos" },
  { id: "tb-settings", label: "Ajustes", Component: TbSettings, group: "procesos" },
  { id: "fa-chart-bar", label: "Gráfico", Component: FaChartBar, group: "procesos" },
  { id: "lu-bar-chart", label: "Gráfico", Component: LuChartBar, group: "procesos" },
  { id: "pi-chart-bar", label: "Gráfico", Component: PiChartBar, group: "procesos" },
  { id: "hi-chart-bar", label: "Gráfico", Component: HiChartBar, group: "procesos" },
  { id: "fa-tasks", label: "Tareas", Component: FaTasks, group: "procesos" },
  { id: "fa-check-circle", label: "Verificado", Component: FaCheckCircle, group: "procesos" },
  { id: "lu-badge-check", label: "Verificado", Component: LuBadgeCheck, group: "procesos" },
  { id: "pi-shield-check", label: "Verificado", Component: PiShieldCheck, group: "procesos" },
  { id: "lu-shield-check", label: "Verificado", Component: LuShieldCheck, group: "procesos" },
  { id: "fa-clipboard-check", label: "Auditoría", Component: FaClipboardCheck, group: "procesos" },
  { id: "hi-clipboard-check", label: "Auditoría", Component: HiClipboardDocumentCheck, group: "procesos" },
  { id: "hi-clipboard-doc", label: "Auditoría", Component: HiClipboardDocumentCheck, group: "procesos" },
  { id: "pi-clipboard-text", label: "Procedimiento", Component: PiClipboardText, group: "procesos" },
  { id: "pi-list-checks", label: "Procedimiento", Component: PiListChecks, group: "procesos" },
  { id: "lu-list-checks", label: "Procedimiento", Component: LuListChecks, group: "procesos" },
  { id: "tb-clipboard-list", label: "Procedimiento", Component: TbClipboardList, group: "procesos" },
  { id: "tb-clipboard-check", label: "Procedimiento", Component: TbClipboardCheck, group: "procesos" },
  { id: "fa-balance-scale", label: "Normativa", Component: FaBalanceScale, group: "procesos" },
  { id: "fa-calculator", label: "Cálculo", Component: FaCalculator, group: "procesos" },
  { id: "fa-project-diagram", label: "Diagrama", Component: FaProjectDiagram, group: "procesos" },
  { id: "fa-sitemap", label: "Estructura", Component: FaSitemap, group: "procesos" },
  { id: "fa-search", label: "Búsqueda", Component: FaSearch, group: "procesos" },
  { id: "fa-tools", label: "Herramientas", Component: FaTools, group: "procesos" },
  { id: "lu-wrench", label: "Herramientas", Component: LuWrench, group: "procesos" },
  { id: "lu-layers", label: "Capas", Component: LuLayers, group: "procesos" },
  { id: "tb-template", label: "Plantilla", Component: TbTemplate, group: "procesos" },

  //* Organización (8)
  { id: "fa-users", label: "Usuarios", Component: FaUsers, group: "organizacion" },
  { id: "pi-users", label: "Usuarios", Component: PiUsersFour, group: "organizacion" },
  { id: "lu-users", label: "Usuarios", Component: LuUsers, group: "organizacion" },
  { id: "tb-users", label: "Usuarios", Component: TbUsers, group: "organizacion" },
  { id: "tb-users-group", label: "Equipo", Component: TbUsersGroup, group: "organizacion" },
  { id: "fa-user-tie", label: "Personal", Component: FaUserTie, group: "organizacion" },
  { id: "fa-user-md-org", label: "Profesional", Component: FaUserMd, group: "organizacion" },
  { id: "fa-user-shield", label: "Admin", Component: FaUserShield, group: "organizacion" },
  { id: "fa-user-cog", label: "Configurador", Component: FaUserCog, group: "organizacion" },
  { id: "pi-user-gear", label: "Admin", Component: PiUserGear, group: "organizacion" },
  { id: "lu-user-cog", label: "Admin", Component: LuUserCog, group: "organizacion" },
  { id: "pi-user-circle", label: "Usuario", Component: PiUserCircle, group: "organizacion" },
  { id: "lu-user", label: "Usuario", Component: LuUser, group: "organizacion" },
  { id: "tb-user", label: "Usuario", Component: TbUser, group: "organizacion" },
  { id: "fa-building", label: "Edificio", Component: FaBuilding, group: "organizacion" },
  { id: "pi-buildings", label: "Edificios", Component: PiBuildings, group: "organizacion" },
  { id: "lu-building", label: "Edificio", Component: LuBuilding2, group: "organizacion" },
  { id: "hi-building", label: "Sede", Component: HiBuildingOffice, group: "organizacion" },
  { id: "fa-city", label: "Ciudad", Component: FaCity, group: "organizacion" },
  { id: "fa-university", label: "Institución", Component: FaUniversity, group: "organizacion" },
  { id: "fa-school", label: "Capacitación", Component: FaSchool, group: "organizacion" },
  { id: "fa-briefcase", label: "Cartera", Component: FaBriefcase, group: "organizacion" },
  { id: "fa-industry", label: "Operaciones", Component: FaIndustry, group: "organizacion" },
  { id: "hi-calendar", label: "Agenda", Component: HiCalendar, group: "organizacion" },
  { id: "fa-calendar", label: "Calendario", Component: FaCalendarAlt, group: "organizacion" },

  //* General (8)
  { id: "fa-star", label: "Destacado", Component: FaStar, group: "general" },
  { id: "lu-star", label: "Destacado", Component: LuStar, group: "general" },
  { id: "pi-star", label: "Destacado", Component: PiStar, group: "general" },
  { id: "hi-star", label: "Destacado", Component: HiStar, group: "general" },
  { id: "fa-flag", label: "Bandera", Component: FaFlag, group: "general" },
  { id: "lu-flag", label: "Bandera", Component: LuFlag, group: "general" },
  { id: "tb-flag", label: "Bandera", Component: TbFlag, group: "general" },
  { id: "pi-flag", label: "Bandera", Component: PiFlagPennant, group: "general" },
  { id: "fa-bookmark", label: "Marcador", Component: FaBookmark, group: "general" },
  { id: "hi-bookmark", label: "Marcador", Component: HiBookmark, group: "general" },
  { id: "pi-bookmark", label: "Marcador", Component: PiBookmarkSimple, group: "general" },
  { id: "fa-tag", label: "Etiqueta", Component: FaTag, group: "general" },
  { id: "fa-lightbulb", label: "Idea", Component: FaLightbulb, group: "general" },
  { id: "hi-lightbulb", label: "Idea", Component: HiLightBulb, group: "general" },
  { id: "pi-lightbulb", label: "Idea", Component: PiLightbulb, group: "general" },
  { id: "fa-key", label: "Clave", Component: FaKey, group: "general" },
  { id: "pi-key", label: "Clave", Component: PiKey, group: "general" },
  { id: "lu-key", label: "Clave", Component: LuKeyRound, group: "general" },
  { id: "lu-circle-alert", label: "Alerta", Component: LuCircleAlert, group: "general" },
];

export const getIconById = (id: string | null | undefined): IconType | null =>
  ICON_CATALOG.find((entry) => entry.id === id)?.Component ?? null;
